"""
Django settings for benefit project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@*5_m#jm1208l0)p_%q-ku%80!d5_g$^nm7l9cd1z2685#pg23'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ADMINS = [('Reeta', 'reeta.prajapati@gate6.com'),]

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = False

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'benefitapp'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
    'benefitapp.disable.DisableCSRF'
)

ROOT_URLCONF = 'benefit.urls'

"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request'
            ],
        },
    },
]
"""

WSGI_APPLICATION = 'benefit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'benefitstg',
        'USER': 'benefitstg',
        'PASSWORD': 'bene#78^szr2D',
        'HOST': 'localhost',
        'PORT': '',
    }
}

DATABASE_NAME = 'benefitstg'
DATABASE_ENGINE = 'django.db.backends.mysql'
DATABASE_USER = 'benefitstg'
DATABASE_PASSWORD = 'bene#78^szr2D'
DATABASE_HOST = 'localhost'
DATABASE_PORT = ''

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/images/'

#TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]

#REST_SESSION_LOGIN = False
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#SITE_ID = 1
#ACCOUNT_EMAIL_REQUIRED = True
#ACCOUNT_AUTHENTICATION_METHOD = 'username'
#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

#REST_FRAMEWORK = {
#    'DEFAULT_AUTHENTICATION_CLASSES': (
#        'rest_framework.authentication.SessionAuthentication',
#        'rest_framework.authentication.TokenAuthentication',
#    )
#}

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'gate6.info@gate6.com'
EMAIL_HOST_PASSWORD = 'Goole2010A!!'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

MEDIA_ROOT = '/home/benefitstg/public_html/benefit/benefitapp/static/'
MEDIA_URL = 'profileimages/'
POST_MEDIA_URL = 'post/'
PRODUCT_MEDIA_URL = 'products/'
BANNER_URL = 'profilebanner/'

BASE_URL = "http://benefit.test.gate6.com:8001"
VIMEO_TOKEN = '8f5f39bbe9f377fe40bfbd8609f82029'

#MEDIA_ROOT = os.path.join(BASE_DIR, 'profile')
#MEDIA_URL = '/media/'

TEMPLATE_DIRS = ( os.path.join(BASE_DIR, 'templates'), )